# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main", "Dev" ]
  pull_request:
    branches: [ "main", "Dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore WebShop/WebShop.slnx
    - name: Build
      run: dotnet build WebShop/WebShop.slnx --no-restore
    - name: Test
      run: dotnet test WebShop/WebShop.slnx --no-build --verbosity normal
